version: '2'
services:
  cmpdregcustomlabsynch:
    image: mcneilco/cmpdreg-custom-labsynch:latest
    volumes:
     - /usr/local/tomcat/webapps/cmpdreg/client/custom
     - /usr/local/tomcat/webapps/ROOT
     - /root/.chemaxon
    command: /bin/true
  cmpdreggui:
    image: mcneilco/cmpdreggui:development
    volumes_from:
     - cmpdregcustomlabsynch
    volumes:
     - /usr/local/tomcat/webapps/cmpdreg/client
    command: /bin/true
  cmpdreg:
    image: mcneilco/cmpdreg:development
    volumes_from:
     - cmpdreggui
    volumes:
      - /usr/local/tomcat/webapps/cmpdreg
      - filestore:/home/runner/privateUploads
    command: /bin/true
  tomcat:
    volumes_from:
      - cmpdreg
    env_file:
      - ./conf/docker/cmpdreg/environment/cmpdreg.env
  acas:
    volumes:
      - ./conf/docker/cmpdreg/conf/cmpdreg.properties:/home/runner/build/conf/cmpdreg.properties