acas:
  build: .
  restart: always
  ports:
   - "3000:3000"
   - "1080:1080"
   - "8787:8787"
   - "8081:8080"
  volumes_from:
   - filestore
  links:
   - db
   - tomcat
  environment:
   - APP_NAME=$TAG
  volumes:
   - ./bin/environments/acas:/mnt/environments/acas
   - /home/runner/build/conf/compiled
   - .:/home/runner/acas
  #command: ["bin/acas-docker.sh", "run"]
  command: ["bin/acas-docker.sh", "run", "all", "dev"]
dbstore:
  build: .
  volumes:
    - /var/lib/postgresql
  command: /bin/true
db:
  image: mcneilco/acas-postgres:latest
  restart: always
  volumes:
   - ./bin/environments:/mnt/environments
  volumes_from:
   - dbstore
  ports:
   - "5432:5432"
filestore:
  build: .
  volumes:
    - /home/runner/build/privateUploads
  command: /bin/true
roo:
  image: mcneilco/acas-roo-server:$TAG
  volumes:
   - /usr/local/tomcat/webapps/acas
  command: /bin/true
tomcat:
  image: mcneilco/tomcat-maven
  restart: always
  ports:
   - "8080:8080"
  volumes_from:
   - filestore
   - roo
  links:
   - db
  environment:
   - CATALINA_OPTS=-Xms512M -Xmx1024M -XX:MaxPermSize=512m
  volumes:
   - ./bin/environments/acas:/mnt/environments/acas
  command: catalina.sh run
