version: '2'
services:
  acas:
    build: .
    restart: always
    ports:
     - "3000:3000"
     - "3001:3001"
    environment:
     - APP_NAME=$TAG
     - PREPARE_MODULE_CONF_JSON=true
    volumes:
     - /home/runner/build/src/r
     - /home/runner/build/privateUploads
     - /home/runner/build/bin
     - /home/runner/build/conf/compiled
     - /home/runner/logs
     # Dev volumes below this line
    env_file:
      - ./bin/environments/acas/acas.env
    command: ["bin/acas-docker.sh", "run", "acas", "start"]
  rservices:
    image: mcneilco/racas:ACASDEV-409-build-tools-restructuring
    restart: always
    ports:
     - "1080:1080"
    environment:
     - PREPARE_MODULE_CONF_JSON=false
     - PREPARE_CONFIG_FILES=false
    volumes_from:
     - acas
    command: ["bin/acas-docker.sh", "run", "rservices"]
  db:
    image: mcneilco/acas-postgres:ACASDEV-409-build-tools-restructuring
    restart: always
    volumes:
     - dbstore:/var/lib/postgresql
    env_file:
      - ./bin/environments/postgres/postgres.env
      - ./bin/environments/db/db.env
      - ./bin/environments/acas/acas.env
      - ./bin/environments/cmpdreg/cmpdreg.env
      - ./bin/environments/seurat/seurat.env
    ports:
     - "5432:5432"
  tomcat:
    image: mcneilco/tomcat-maven
    restart: always
    depends_on: 
     - db
    ports:
     - "8080:8080"
    environment:
     - CATALINA_OPTS=-Xms512M -Xmx1024M -XX:MaxPermSize=512m
    volumes_from:
     - roo
     - acas
    env_file:
      - ./bin/environments/acas/acas.env
      - ./bin/environments/roo/roo.env
    command: catalina.sh run
  roo:
    image: mcneilco/acas-roo-server:ACASDEV-409-build-tools-restructuring
    volumes:
     - /usr/local/tomcat/webapps/acas
    command: /bin/true
volumes:
  dbstore:
