version: '2'
services:
  acas:
#    build: .
    image: mcneilco/acas:1.9.0-release
    restart: always
    ports:
     - "3000:3000"
     - "3001:3001"
     - "5858:5858"
    environment:
     - APP_NAME=1.9.0
     - PREPARE_MODULE_CONF_JSON=true
     - PREPARE_CONFIG_FILES=true
     - DOCKER_HOST_IP=localhost
     - NODE_ENV=integration
    volumes:
     - filestore:/home/runner/build/privateUploads
     - logs:/home/runner/logs
     - /home/runner/build/bin
     - /home/runner/build/src/r
     - /home/runner/build/conf/compiled
     # Please add any dev volumes below this line
     # - ./:/home/runner/acas
     # - ./modules/BuildUtilities/:/home/runner/acas/modules/BuildUtilities
    env_file:
      - ./conf/docker/acas/environment/acas.env
# Dev Command
    command: ["bin/acas.sh", "run", "acas", "dev"]
# Start command
#    command: ["bin/acas.sh", "run", "acas", "start"]
  rservices:
    image: mcneilco/racas:1.9.0-release
    restart: always
    ports:
     - "1080:1080"
    environment:
     - PREPARE_MODULE_CONF_JSON=false
     - PREPARE_CONFIG_FILES=false
    volumes_from:
     - acas
    volumes:
      - filestore:/home/runner/build/privateUploads
      - logs:/home/runner/logs
    command: ["bin/acas.sh", "run", "rservices"]
  db:
    image: mcneilco/acas-postgres:development
    restart: always
    volumes:
     - dbstore:/var/lib/postgresql/data
    env_file:
      - ./conf/docker/postgres/environment/postgres.env
      - ./conf/docker/db/environment/db.env
      - ./conf/docker/acas/environment/acas.env
      - ./conf/docker/cmpdreg/environment/cmpdreg.env
      - ./conf/docker/seurat/environment/seurat.env
    ports:
     - "5432:5432"
  tomcat:
    image: mcneilco/tomcat-maven
    restart: always
    depends_on:
     - db
    ports:
     - "8080:8080"
     - "8000:8000"
    environment:
     - CATALINA_OPTS=-Xms512M -Xmx1024M -XX:MaxPermSize=512m
     - JAVA_OPTS=-Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=8000
    volumes_from:
     - roo
     - acas
    env_file:
      - ./conf/docker/acas/environment/acas.env
      - ./conf/docker/roo/environment/roo.env
    command: catalina.sh run
  roo:
    image: mcneilco/acas-roo-server:1.9.0-release
    volumes:
     - /usr/local/tomcat/webapps/acas
    command: /bin/true
volumes:
  dbstore:
  filestore:
  logs:
